In [1]:
from datasets import Dataset

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import re

c:\Users\agsto\Desktop\CMPE-252-summary-project\summary_env\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [4]:
import torch

print("PyTorch version:", torch.__version__)
print("CUDA available:", torch.cuda.is_available())       # True if GPU is usable
print("CUDA version:", torch.version.cuda)                # CUDA version PyTorch was built with
print("Number of GPUs:", torch.cuda.device_count())       # Number of GPUs detected
if torch.cuda.is_available():
    print("GPU name:", torch.cuda.get_device_name(0))

PyTorch version: 2.10.0+cu126
CUDA available: True
CUDA version: 12.6
Number of GPUs: 1
GPU name: NVIDIA GeForce RTX 4070 SUPER

## Importing and cleaning data set

In [5]:
section_path = "section_train_0.parquet" #file path
section = pd.read_parquet(section_path)

In [6]:
documention_path_0 = "document_train_0.parquet" #file path
document_0 = pd.read_parquet(documention_path_0)

documention_path_1 = "document_train_1.parquet"
document_1 = pd.read_parquet(documention_path_1)

documention_path_2 = "document_train_2.parquet"
document_2 = pd.read_parquet(documention_path_2)

documention_path_3 = "document_train_3.parquet"
document_3 = pd.read_parquet(documention_path_3)

In [7]:
document = pd.concat([document_0, document_1, document_2, document_3])

In [8]:
document['abstract'] = document['abstract'].str.replace(' \n', '', regex=False) #remove \n
document['abstract'] = document['abstract'].str.replace(r'@\w+', '', regex=True) # remove @ formulas
document['abstract'] = document['abstract'].str.replace('  ', ' ', regex=False) #replace double space with single space

document['article'] = document['article'].str.replace(r'@\w+', '', regex=True) # remove @ formulas
document['article'] = document['article'].str.replace('  ', ' ', regex=False) #replace double space with single space

## Remove samples with missing info and samples with too much noise

In [9]:
article_summary = document['article'].str.len().describe()
article_summary

count     54144.000000
mean      30196.147292
std       22630.985389
min           0.000000
25%       16117.500000
50%       24903.000000
75%       38290.500000
max      607645.000000
Name: article, dtype: float64

In [10]:
abstract_summary = document['abstract'].str.len().describe()
abstract_summary

count    54144.000000
mean      1490.463542
std       2872.869021
min          7.000000
25%        659.000000
50%        938.000000
75%       1324.000000
max      69493.000000
Name: abstract, dtype: float64

In [11]:
document = document[document['article'].str.len() >= article_summary['25%']] 
document = document[document['article'].str.len() <= article_summary['75%']]  

document = document[document['abstract'].str.len() >= abstract_summary['25%']]
document = document[document['abstract'].str.len() <= abstract_summary['75%']]

document = document.drop_duplicates()
document = document.reset_index(drop=True)

## BART (No training yet)

In [15]:
from transformers import BartTokenizer, BartForConditionalGeneration
import torch

model_name = "facebook/bart-large-cnn"

tokenizer = BartTokenizer.from_pretrained(model_name)
model = BartForConditionalGeneration.from_pretrained(model_name, output_attentions=True)

model.config.output_attentions = True
model.config.return_dict = True

model.eval()

Loading weights: 100%|██████████| 511/511 [00:00<00:00, 1148.34it/s, Materializing param=model.encoder.layers.11.self_attn_layer_norm.weight]
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

BartForConditionalGeneration(
  (model): BartModel(
    (shared): BartScaledWordEmbedding(50264, 1024, padding_idx=1)
    (encoder): BartEncoder(
      (embed_tokens): BartScaledWordEmbedding(50264, 1024, padding_idx=1)
      (embed_positions): BartLearnedPositionalEmbedding(1026, 1024)
      (layers): ModuleList(
        (0-11): 12 x BartEncoderLayer(
          (self_attn): BartAttention(
            (k_proj): Linear(in_features=1024, out_features=1024, bias=True)
            (v_proj): Linear(in_features=1024, out_features=1024, bias=True)
            (q_proj): Linear(in_features=1024, out_features=1024, bias=True)
            (out_proj): Linear(in_features=1024, out_features=1024, bias=True)
          )
          (self_attn_layer_norm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
          (activation_fn): GELUActivation()
          (fc1): Linear(in_features=1024, out_features=4096, bias=True)
          (fc2): Linear(in_features=4096, out_features=1024, bias=True)
          (final_layer_norm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
        )
      )
      (layernorm_embedding): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
    )
    (decoder): BartDecoder(
      (embed_tokens): BartScaledWordEmbedding(50264, 1024, padding_idx=1)
      (embed_positions): BartLearnedPositionalEmbedding(1026, 1024)
      (layers): ModuleList(
        (0-11): 12 x BartDecoderLayer(
          (self_attn): BartAttention(
            (k_proj): Linear(in_features=1024, out_features=1024, bias=True)
            (v_proj): Linear(in_features=1024, out_features=1024, bias=True)
            (q_proj): Linear(in_features=1024, out_features=1024, bias=True)
            (out_proj): Linear(in_features=1024, out_features=1024, bias=True)
          )
          (activation_fn): GELUActivation()
          (self_attn_layer_norm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
          (encoder_attn): BartAttention(
            (k_proj): Linear(in_features=1024, out_features=1024, bias=True)
            (v_proj): Linear(in_features=1024, out_features=1024, bias=True)
            (q_proj): Linear(in_features=1024, out_features=1024, bias=True)
            (out_proj): Linear(in_features=1024, out_features=1024, bias=True)
          )
          (encoder_attn_layer_norm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
          (fc1): Linear(in_features=1024, out_features=4096, bias=True)
          (fc2): Linear(in_features=4096, out_features=1024, bias=True)
          (final_layer_norm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
        )
      )
      (layernorm_embedding): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
    )
  )
  (lm_head): Linear(in_features=1024, out_features=50264, bias=False)
)

In [16]:
text = document['article'][0]

inputs = tokenizer(text, return_tensors="pt", max_length=1024, truncation=True)

generated = model.generate(
    inputs["input_ids"],
    num_beams=4,
    max_length=500,
    min_length=100,
    #length_penalty=2.0, # can change min and max length as well as this to see if we want to have the summary be more brief     
    early_stopping=True,
    no_repeat_ngram_size=3,
    do_sample=False,
    return_dict_in_generate=True
)

generated_ids = generated.sequences

summary = tokenizer.decode(generated_ids[0], skip_special_tokens=True)
print(summary)

#for attention values
outputs = model(
    input_ids=inputs["input_ids"],
    decoder_input_ids=generated_ids,
    output_attentions=True,
    return_dict=True
)

cross_attentions = outputs.cross_attentions

additive models provide an important family of models for semiparametric regression or classification. Some reasons for the success of additive models are their increased flexibility when compared to linear or generalized linear models and their increased interpretability. In this paper we address the open question whether an svm with an additive kernel can provide a substantially better learning rate in high dimensions. We will not address the question how to check whether the assumption of an additive model is satisfied because this would be a topic of a paper of its own.

In [17]:
print(len(cross_attentions))
print(cross_attentions[0].shape)

12
torch.Size([1, 16, 105, 1024])

In [18]:
cross_attentions

(tensor([[[[1.9530e-01, 6.6491e-07, 8.6813e-10,  ..., 4.6027e-08,
            1.8740e-08, 3.3442e-02],
           [7.8566e-02, 3.6558e-05, 1.2620e-08,  ..., 3.2075e-08,
            1.8732e-09, 4.3937e-02],
           [1.4969e-03, 9.6271e-01, 2.0434e-06,  ..., 9.9358e-10,
            1.5781e-08, 1.2946e-03],
           ...,
           [2.9099e-03, 1.7626e-07, 4.7626e-07,  ..., 3.8807e-09,
            3.5607e-07, 9.4704e-04],
           [1.6940e-01, 9.5440e-07, 6.9736e-07,  ..., 5.7952e-09,
            1.4324e-08, 6.0313e-02],
           [7.8984e-02, 1.0426e-08, 5.9409e-11,  ..., 3.7038e-09,
            1.4941e-07, 8.5193e-02]],

          [[7.5060e-02, 1.1381e-04, 1.7044e-04,  ..., 1.7028e-04,
            1.5922e-04, 3.0086e-02],
           [8.7623e-02, 6.6379e-04, 3.1574e-04,  ..., 4.5471e-05,
            4.4424e-05, 2.2373e-02],
           [2.5617e-01, 1.4498e-03, 4.5393e-04,  ..., 5.4525e-05,
            8.1151e-05, 2.6895e-02],
           ...,
           [2.5342e-01, 7.4780e-04, 4.3976e-04,  ..., 2.0800e-04,
            1.4122e-04, 3.9974e-02],
           [1.9577e-01, 4.7516e-04, 3.1104e-04,  ..., 1.9760e-05,
            1.0769e-05, 2.9712e-02],
           [5.6435e-02, 2.3952e-03, 7.9248e-04,  ..., 6.1727e-05,
            5.8592e-05, 1.7348e-02]],

          [[9.3938e-02, 1.0555e-03, 7.5077e-04,  ..., 1.3038e-04,
            1.7910e-04, 1.0925e-01],
           [7.7801e-02, 1.3454e-02, 1.2855e-03,  ..., 3.8873e-05,
            4.6689e-05, 4.4522e-02],
           [6.2940e-02, 6.4286e-02, 2.3435e-03,  ..., 4.9867e-05,
            1.2251e-05, 1.5143e-01],
           ...,
           [3.3694e-01, 9.1070e-04, 5.9563e-04,  ..., 9.2075e-05,
            8.1678e-05, 2.5907e-02],
           [2.5798e-01, 1.4465e-05, 2.8417e-05,  ..., 5.2632e-06,
            1.4553e-06, 3.2249e-03],
           [1.4376e-01, 4.9201e-03, 1.5625e-03,  ..., 1.8476e-04,
            1.4628e-04, 4.2315e-02]],

          ...,

          [[3.8571e-02, 8.9348e-05, 1.2877e-05,  ..., 5.1119e-07,
            8.6516e-07, 9.5180e-01],
           [3.7442e-02, 8.0704e-04, 3.9497e-05,  ..., 4.8398e-07,
            6.8139e-07, 9.4440e-01],
           [1.8269e-01, 2.6960e-03, 4.6926e-04,  ..., 8.6935e-06,
            2.0406e-05, 1.2573e-02],
           ...,
           [5.8844e-04, 4.8403e-04, 1.0643e-03,  ..., 1.8557e-04,
            8.9640e-05, 2.2900e-04],
           [3.4967e-06, 6.3323e-03, 1.9245e-04,  ..., 5.0009e-04,
            2.4119e-04, 4.8535e-05],
           [2.3161e-04, 1.3025e-02, 8.8536e-04,  ..., 3.8170e-05,
            2.7544e-05, 8.8938e-04]],

          [[9.5807e-03, 1.7259e-03, 5.1993e-05,  ..., 3.9936e-04,
            2.8333e-04, 1.0584e-02],
           [1.6501e-02, 5.9476e-04, 4.0979e-05,  ..., 8.3757e-04,
            6.2097e-04, 1.3196e-01],
           [1.3667e-01, 1.6556e-03, 1.5563e-03,  ..., 9.2265e-05,
            4.4803e-05, 1.3715e-02],
           ...,
           [1.4260e-01, 6.1275e-03, 1.3321e-03,  ..., 2.4794e-04,
            1.2108e-04, 2.2402e-02],
           [2.0537e-02, 1.7628e-03, 2.9436e-04,  ..., 9.4620e-04,
            8.9081e-04, 1.0565e-02],
           [5.2642e-03, 1.3122e-03, 5.5900e-04,  ..., 5.0143e-04,
            2.5920e-04, 3.0597e-03]],

          [[3.4182e-02, 2.3267e-04, 2.6068e-04,  ..., 4.4422e-04,
            1.0055e-04, 2.0343e-02],
           [3.9598e-02, 5.4865e-04, 5.2417e-04,  ..., 5.6376e-05,
            5.8552e-05, 1.7304e-02],
           [6.5493e-06, 9.1755e-01, 3.2171e-05,  ..., 2.4589e-09,
            5.3024e-10, 5.9300e-06],
           ...,
           [1.8832e-03, 1.6296e-04, 2.9215e-05,  ..., 1.9981e-06,
            2.3943e-06, 1.8098e-03],
           [4.6251e-01, 9.2370e-05, 5.7185e-05,  ..., 8.8647e-06,
            4.3526e-06, 7.5892e-02],
           [1.5064e-02, 6.2456e-05, 1.7307e-05,  ..., 4.1388e-06,
            8.3228e-04, 2.4235e-02]]]], grad_fn=<SoftmaxBackward0>),
 tensor([[[[1.4890e-05, 3.5806e-04, 3.3310e-03,  ..., 2.1576e-04,
            2.3602e-04, 8.2335e-06],
           [1.2257e-05, 3.5459e-04, 2.9710e-03,  ..., 2.1659e-04,
            2.1129e-04, 6.6404e-06],
           [3.1707e-03, 8.7119e-01, 4.6280e-04,  ..., 2.0614e-09,
            3.5094e-08, 5.3412e-03],
           ...,
           [1.5829e-04, 2.5980e-08, 8.7930e-09,  ..., 4.7295e-10,
            1.6584e-09, 9.2263e-05],
           [6.4740e-03, 4.7103e-06, 5.6211e-06,  ..., 4.1946e-08,
            1.3331e-07, 2.1089e-03],
           [1.1386e-02, 9.4080e-08, 4.7957e-07,  ..., 3.0807e-07,
            1.5992e-07, 2.2282e-03]],

          [[4.4115e-06, 7.2069e-06, 2.5693e-04,  ..., 5.3908e-05,
            6.4617e-05, 9.3502e-01],
           [4.8047e-06, 6.9430e-06, 2.4046e-04,  ..., 5.2360e-05,
            6.5449e-05, 9.3602e-01],
           [1.9518e-02, 1.8148e-02, 1.8630e-02,  ..., 2.5134e-05,
            4.2724e-05, 1.5028e-03],
           ...,
           [2.6626e-02, 7.2042e-04, 1.6188e-04,  ..., 3.1522e-05,
            2.3134e-05, 7.2830e-05],
           [2.3296e-02, 1.1632e-03, 4.2494e-04,  ..., 5.1997e-05,
            5.8220e-05, 1.5196e-04],
           [1.0345e-01, 1.6555e-03, 7.0585e-04,  ..., 3.0982e-05,
            3.6340e-05, 1.4903e-04]],

          [[3.0835e-06, 1.2404e-05, 4.4528e-05,  ..., 2.6114e-04,
            1.3579e-04, 2.2230e-05],
           [2.2466e-06, 1.1382e-05, 4.1555e-05,  ..., 2.4527e-04,
            1.2100e-04, 1.9915e-05],
           [1.9263e-03, 1.0215e-01, 2.4948e-03,  ..., 1.0013e-05,
            1.1775e-05, 1.3029e-01],
           ...,
           [6.7141e-05, 2.5356e-06, 6.5602e-08,  ..., 4.3660e-08,
            9.0412e-09, 1.1344e-04],
           [1.1655e-04, 4.3877e-05, 1.6029e-07,  ..., 1.2380e-07,
            1.3617e-08, 1.5576e-03],
           [1.0315e-02, 1.6859e-02, 1.6395e-03,  ..., 3.1110e-05,
            3.3106e-05, 3.6192e-02]],

          ...,

          [[1.1943e-05, 3.8101e-05, 2.2508e-05,  ..., 2.8703e-03,
            7.4160e-03, 3.0586e-05],
           [1.2572e-05, 4.4319e-05, 2.4188e-05,  ..., 2.7808e-03,
            7.2766e-03, 3.4564e-05],
           [4.8142e-02, 2.8981e-02, 4.1138e-03,  ..., 2.1038e-05,
            1.7088e-05, 1.1998e-02],
           ...,
           [2.6308e-02, 1.1878e-03, 6.7751e-04,  ..., 5.4457e-04,
            4.9515e-04, 1.5527e-02],
           [1.1413e-02, 5.5029e-03, 1.6940e-03,  ..., 2.8524e-04,
            2.8454e-04, 8.5142e-03],
           [4.5491e-02, 9.7057e-05, 4.9807e-04,  ..., 2.5254e-05,
            2.0575e-05, 1.7193e-04]],

          [[4.5617e-06, 1.3004e-04, 3.8521e-04,  ..., 3.2103e-06,
            4.1557e-07, 3.0103e-05],
           [3.9822e-06, 1.0595e-04, 3.4915e-04,  ..., 3.3740e-06,
            4.3964e-07, 2.1221e-05],
           [7.4349e-03, 1.0030e-01, 9.9543e-03,  ..., 6.3428e-07,
            3.7065e-07, 2.0109e-03],
           ...,
           [1.4972e-04, 1.0577e-07, 6.1638e-11,  ..., 9.9815e-10,
            1.5397e-09, 3.6877e-05],
           [5.0349e-03, 6.1428e-05, 5.9380e-08,  ..., 2.7984e-11,
            6.0486e-11, 2.2409e-03],
           [4.4177e-04, 1.9397e-04, 9.3225e-06,  ..., 2.0648e-06,
            2.2197e-06, 8.2141e-01]],

          [[1.0622e-04, 6.5749e-05, 1.1070e-04,  ..., 1.3224e-04,
            5.2141e-05, 1.5722e-05],
           [8.7706e-05, 6.1435e-05, 9.9511e-05,  ..., 1.2898e-04,
            4.8204e-05, 1.4791e-05],
           [4.6331e-04, 3.9436e-01, 1.0801e-03,  ..., 1.9344e-08,
            8.1049e-08, 6.6521e-03],
           ...,
           [1.8890e-04, 1.4015e-05, 4.9451e-07,  ..., 7.0121e-08,
            6.7200e-08, 2.6134e-04],
           [4.5108e-05, 3.8662e-03, 1.3083e-05,  ..., 6.8569e-07,
            8.9931e-07, 1.7554e-03],
           [3.5942e-01, 5.9702e-04, 2.5513e-03,  ..., 1.5764e-04,
            5.0822e-06, 7.6971e-03]]]], grad_fn=<SoftmaxBackward0>),
 tensor([[[[1.6672e-04, 5.2073e-05, 2.1235e-04,  ..., 2.2181e-04,
            3.2036e-04, 6.5674e-06],
           [1.6788e-04, 5.2303e-05, 2.1288e-04,  ..., 2.2169e-04,
            3.2049e-04, 6.6074e-06],
           [6.4511e-02, 2.8319e-01, 3.7744e-02,  ..., 1.6301e-07,
            3.9496e-07, 8.5686e-03],
           ...,
           [2.2313e-03, 2.2164e-05, 8.7933e-07,  ..., 7.7812e-10,
            2.6146e-10, 6.8061e-04],
           [2.6239e-02, 6.4983e-04, 3.0493e-05,  ..., 9.0084e-06,
            4.5223e-06, 1.7997e-02],
           [1.5356e-01, 5.3205e-04, 1.6056e-04,  ..., 3.5437e-06,
            4.7601e-06, 4.7388e-03]],

          [[6.0048e-03, 1.7890e-03, 7.3582e-04,  ..., 4.9683e-05,
            5.6153e-05, 2.1229e-04],
           [6.0126e-03, 1.7848e-03, 7.3328e-04,  ..., 4.9345e-05,
            5.5834e-05, 2.1329e-04],
           [5.7011e-02, 5.4627e-03, 1.9738e-03,  ..., 1.0533e-05,
            2.8285e-05, 3.1800e-02],
           ...,
           [8.5175e-02, 7.0885e-05, 1.3709e-05,  ..., 4.3201e-06,
            2.9026e-06, 7.4957e-02],
           [3.9240e-02, 4.7490e-04, 9.7078e-06,  ..., 1.2872e-05,
            2.9988e-06, 3.9338e-02],
           [1.2993e-02, 3.6607e-04, 1.6851e-04,  ..., 1.4554e-05,
            1.1379e-05, 6.9716e-03]],

          [[5.6406e-03, 5.2831e-03, 1.0788e-02,  ..., 3.1870e-05,
            6.5842e-05, 3.8001e-03],
           [5.6827e-03, 5.2938e-03, 1.0824e-02,  ..., 3.1859e-05,
            6.5705e-05, 3.8208e-03],
           [2.8429e-05, 4.3743e-02, 3.8363e-04,  ..., 4.0047e-10,
            1.2113e-09, 1.9810e-03],
           ...,
           [1.6680e-04, 4.2795e-08, 1.2456e-08,  ..., 3.7950e-07,
            5.7208e-08, 1.3867e-04],
           [6.2109e-03, 1.3693e-04, 2.1776e-06,  ..., 1.2620e-05,
            1.0472e-06, 2.5850e-03],
           [2.2278e-02, 1.2411e-03, 1.7118e-03,  ..., 9.8095e-06,
            2.2786e-05, 1.0554e-02]],

          ...,

          [[4.6275e-01, 6.2565e-04, 2.9992e-03,  ..., 3.6461e-05,
            1.5375e-04, 1.8410e-05],
           [4.6526e-01, 6.2568e-04, 2.9925e-03,  ..., 3.6193e-05,
            1.5298e-04, 1.8406e-05],
           [1.1249e-01, 1.9638e-02, 3.0363e-02,  ..., 8.4738e-07,
            3.2098e-06, 3.8515e-03],
           ...,
           [5.6235e-02, 7.5733e-05, 2.0822e-07,  ..., 1.9939e-09,
            3.2672e-09, 9.1845e-04],
           [5.1574e-02, 5.7392e-04, 4.7224e-06,  ..., 3.5015e-07,
            1.2556e-07, 9.7723e-03],
           [2.7630e-01, 1.6012e-02, 7.3832e-04,  ..., 1.5997e-05,
            3.4831e-05, 2.0811e-03]],

          [[9.7238e-01, 1.6523e-07, 1.0279e-07,  ..., 8.4478e-11,
            2.2941e-11, 8.2693e-07],
           [9.7254e-01, 1.6415e-07, 1.0181e-07,  ..., 8.3394e-11,
            2.2646e-11, 8.2340e-07],
           [6.2237e-01, 9.3154e-02, 4.9619e-03,  ..., 2.8721e-07,
            2.4903e-07, 1.0770e-01],
           ...,
           [1.3197e-02, 6.1532e-06, 4.4048e-09,  ..., 5.5705e-05,
            6.6806e-06, 2.7660e-03],
           [1.8185e-01, 2.1673e-03, 7.8045e-07,  ..., 1.5771e-06,
            6.0106e-07, 9.4260e-02],
           [4.8382e-02, 6.2677e-03, 6.5512e-03,  ..., 6.8976e-06,
            4.9640e-06, 3.3786e-02]],

          [[5.1658e-02, 9.2401e-03, 3.5204e-03,  ..., 8.5578e-04,
            6.7647e-04, 1.3893e-02],
           [5.2285e-02, 9.2473e-03, 3.5147e-03,  ..., 8.5347e-04,
            6.7557e-04, 1.4007e-02],
           [6.4617e-01, 5.0848e-03, 1.1031e-02,  ..., 2.9329e-05,
            1.0029e-04, 2.4442e-02],
           ...,
           [6.6534e-01, 3.1752e-05, 9.8395e-06,  ..., 2.9845e-06,
            2.0659e-06, 3.7105e-03],
           [2.2590e-01, 1.0785e-02, 7.3688e-05,  ..., 7.5719e-05,
            7.0873e-05, 8.3041e-03],
           [5.2626e-01, 1.7205e-03, 2.4787e-04,  ..., 3.4999e-06,
            1.4903e-05, 2.3195e-02]]]], grad_fn=<SoftmaxBackward0>),
 tensor([[[[1.0011e-02, 3.1349e-04, 6.5821e-04,  ..., 2.8014e-04,
            2.2539e-04, 3.7039e-04],
           [1.0016e-02, 3.1357e-04, 6.5836e-04,  ..., 2.8012e-04,
            2.2536e-04, 3.7055e-04],
           [1.2352e-01, 2.4094e-02, 1.3360e-02,  ..., 9.1580e-06,
            8.0141e-06, 6.0540e-03],
           ...,
           [4.4610e-02, 1.4210e-02, 1.3207e-03,  ..., 2.0612e-05,
            6.4968e-06, 2.0691e-02],
           [2.6734e-01, 8.9255e-03, 1.6117e-04,  ..., 4.2796e-05,
            3.8372e-05, 2.8947e-01],
           [5.3429e-01, 1.3651e-03, 1.6541e-04,  ..., 1.4116e-07,
            4.9546e-07, 2.3186e-01]],

          [[2.7952e-07, 6.8888e-05, 4.1715e-04,  ..., 1.9891e-04,
            3.3893e-04, 2.6784e-06],
           [2.7972e-07, 6.8917e-05, 4.1729e-04,  ..., 1.9891e-04,
            3.3896e-04, 2.6797e-06],
           [2.5207e-01, 7.4485e-03, 2.8296e-03,  ..., 4.4683e-06,
            7.2124e-06, 4.7296e-03],
           ...,
           [9.3104e-02, 7.9696e-06, 5.2322e-07,  ..., 1.6615e-05,
            4.6944e-05, 2.9516e-03],
           [3.6090e-01, 7.1229e-05, 2.5925e-06,  ..., 1.0679e-05,
            2.0777e-06, 1.4801e-03],
           [3.6826e-01, 4.5442e-04, 3.7153e-04,  ..., 5.3202e-06,
            6.2610e-07, 1.2886e-03]],

          [[2.9663e-11, 4.4110e-06, 1.2924e-04,  ..., 2.0000e-03,
            4.2906e-03, 4.6990e-07],
           [2.9684e-11, 4.4102e-06, 1.2922e-04,  ..., 1.9992e-03,
            4.2890e-03, 4.6981e-07],
           [4.7554e-01, 7.9149e-03, 5.5149e-03,  ..., 6.1973e-05,
            1.0580e-04, 6.5172e-02],
           ...,
           [8.6859e-01, 5.5415e-04, 5.7213e-06,  ..., 2.4717e-05,
            1.0327e-05, 1.0067e-03],
           [2.9184e-01, 3.1027e-03, 8.4580e-06,  ..., 1.0842e-04,
            5.1869e-05, 1.0399e-03],
           [8.3260e-01, 9.6561e-04, 6.1388e-05,  ..., 1.8877e-07,
            8.0616e-08, 1.4336e-02]],

          ...,

          [[3.5456e-01, 1.2656e-07, 1.0208e-07,  ..., 6.4225e-11,
            1.0541e-09, 6.4444e-01],
           [3.5459e-01, 1.2647e-07, 1.0201e-07,  ..., 6.4144e-11,
            1.0528e-09, 6.4440e-01],
           [4.7719e-02, 9.3333e-03, 8.8088e-03,  ..., 9.9333e-05,
            7.8817e-05, 1.6892e-02],
           ...,
           [9.9202e-02, 1.7250e-03, 4.3757e-05,  ..., 5.8161e-06,
            6.8110e-06, 2.3534e-02],
           [3.5615e-02, 5.9536e-03, 4.1823e-04,  ..., 8.1386e-05,
            2.7449e-05, 2.0519e-02],
           [6.2007e-02, 1.3567e-04, 1.4758e-05,  ..., 1.1011e-06,
            3.8397e-07, 1.4876e-02]],

          [[2.9558e-06, 2.3984e-04, 4.5220e-04,  ..., 7.4444e-04,
            7.7556e-04, 5.5720e-05],
           [2.9569e-06, 2.3989e-04, 4.5231e-04,  ..., 7.4441e-04,
            7.7555e-04, 5.5731e-05],
           [5.0920e-02, 5.2501e-03, 1.8334e-03,  ..., 7.3085e-06,
            2.6027e-05, 3.8478e-03],
           ...,
           [3.5593e-02, 6.6816e-04, 1.8032e-05,  ..., 8.5044e-05,
            4.2223e-05, 9.4254e-03],
           [2.1735e-02, 1.3555e-03, 3.3478e-05,  ..., 4.6195e-04,
            4.3160e-04, 2.5067e-02],
           [9.1894e-02, 2.4893e-03, 1.6134e-03,  ..., 1.0829e-05,
            1.3556e-05, 1.2258e-03]],

          [[2.7612e-12, 2.0628e-05, 4.9078e-04,  ..., 1.1852e-04,
            5.7119e-04, 2.0595e-10],
           [2.7641e-12, 2.0637e-05, 4.9076e-04,  ..., 1.1854e-04,
            5.7132e-04, 2.0616e-10],
           [1.7348e-01, 5.9812e-01, 3.0891e-05,  ..., 2.1440e-09,
            6.0878e-08, 1.2587e-01],
           ...,
           [1.9860e-01, 5.4475e-05, 8.0881e-07,  ..., 8.5020e-08,
            9.1762e-07, 2.1931e-02],
           [5.4422e-01, 2.2882e-03, 1.8889e-06,  ..., 4.8687e-07,
            6.8743e-07, 4.9476e-02],
           [4.5670e-01, 1.3083e-04, 1.2661e-05,  ..., 9.2706e-07,
            2.0347e-07, 8.5883e-02]]]], grad_fn=<SoftmaxBackward0>),
 tensor([[[[2.0004e-11, 1.0820e-05, 4.4712e-05,  ..., 1.0925e-04,
            2.4724e-04, 5.2024e-06],
           [2.0005e-11, 1.0820e-05, 4.4713e-05,  ..., 1.0925e-04,
            2.4724e-04, 5.2027e-06],
           [1.1033e-01, 2.1013e-03, 6.8607e-04,  ..., 2.3264e-06,
            5.2159e-06, 5.1299e-05],
           ...,
           [9.5943e-02, 1.4997e-04, 1.0263e-05,  ..., 2.7770e-06,
            1.2497e-06, 5.0541e-03],
           [4.3860e-02, 5.1876e-04, 7.4401e-05,  ..., 9.5593e-06,
            2.0634e-06, 2.1956e-04],
           [4.7121e-02, 4.0204e-04, 1.5700e-05,  ..., 5.9845e-07,
            6.6724e-07, 1.5569e-03]],

          [[4.3576e-12, 1.2937e-05, 2.6710e-04,  ..., 1.7418e-04,
            1.4399e-04, 8.0793e-10],
           [4.3581e-12, 1.2937e-05, 2.6711e-04,  ..., 1.7418e-04,
            1.4399e-04, 8.0798e-10],
           [9.7605e-02, 5.5034e-02, 4.9595e-02,  ..., 1.0891e-07,
            8.2449e-08, 2.5901e-03],
           ...,
           [9.8304e-02, 8.2262e-06, 1.7540e-07,  ..., 6.5536e-08,
            2.0133e-08, 2.2563e-03],
           [4.2885e-02, 6.3621e-04, 8.8751e-06,  ..., 9.0046e-06,
            1.4770e-05, 1.5401e-02],
           [2.9003e-01, 4.3154e-05, 1.0184e-05,  ..., 1.8983e-08,
            5.0617e-09, 9.6305e-04]],

          [[1.5302e-14, 1.0643e-07, 8.9105e-07,  ..., 6.2739e-06,
            1.6950e-06, 1.1714e-09],
           [1.5303e-14, 1.0643e-07, 8.9103e-07,  ..., 6.2737e-06,
            1.6949e-06, 1.1714e-09],
           [3.8297e-02, 2.7421e-02, 4.0224e-03,  ..., 1.6882e-06,
            5.3000e-06, 1.8767e-03],
           ...,
           [3.5725e-01, 3.3482e-05, 7.6997e-07,  ..., 4.9994e-07,
            1.2632e-06, 1.8749e-03],
           [1.0310e-01, 4.8744e-04, 2.2890e-05,  ..., 1.8871e-05,
            3.2229e-05, 7.3230e-03],
           [4.9448e-01, 4.0563e-04, 2.6752e-06,  ..., 5.7962e-07,
            6.7958e-06, 4.0629e-04]],

          ...,

          [[1.1282e-09, 2.4021e-05, 6.3583e-04,  ..., 1.9397e-04,
            6.4490e-04, 9.0743e-08],
           [1.1282e-09, 2.4022e-05, 6.3584e-04,  ..., 1.9397e-04,
            6.4491e-04, 9.0746e-08],
           [6.2010e-02, 5.0899e-03, 4.6326e-03,  ..., 2.2919e-05,
            2.8318e-05, 1.1705e-02],
           ...,
           [1.0444e-02, 2.1230e-03, 1.8377e-05,  ..., 1.3196e-04,
            6.7826e-05, 5.1496e-03],
           [1.3106e-02, 2.5781e-03, 5.9726e-05,  ..., 3.0166e-04,
            2.7830e-04, 1.0777e-02],
           [3.5417e-02, 5.7898e-04, 1.3980e-05,  ..., 3.4469e-07,
            1.5986e-07, 4.2396e-04]],

          [[6.3323e-10, 1.2530e-05, 2.7454e-04,  ..., 1.4184e-04,
            1.4141e-04, 1.7102e-07],
           [6.3326e-10, 1.2530e-05, 2.7454e-04,  ..., 1.4184e-04,
            1.4141e-04, 1.7103e-07],
           [1.3211e-01, 5.1033e-03, 3.9921e-03,  ..., 2.3840e-06,
            3.2913e-06, 2.1555e-03],
           ...,
           [6.7162e-02, 1.8451e-05, 4.3898e-07,  ..., 3.8384e-06,
            1.8355e-06, 9.6051e-04],
           [1.9222e-01, 8.3125e-05, 3.5536e-06,  ..., 6.2959e-06,
            2.4906e-06, 1.2070e-03],
           [4.5258e-03, 6.5837e-04, 1.5091e-05,  ..., 2.0644e-06,
            5.4772e-06, 4.8124e-04]],

          [[3.3148e-12, 2.5285e-07, 9.7570e-05,  ..., 1.6556e-04,
            1.6572e-04, 5.4883e-09],
           [3.3152e-12, 2.5286e-07, 9.7574e-05,  ..., 1.6556e-04,
            1.6572e-04, 5.4884e-09],
           [8.8188e-03, 9.6197e-02, 7.0745e-02,  ..., 7.8963e-07,
            1.7780e-06, 1.0349e-02],
           ...,
           [1.8676e-01, 1.5081e-05, 2.9443e-08,  ..., 3.1318e-07,
            2.9347e-07, 7.8476e-04],
           [2.5318e-01, 1.8356e-04, 2.7822e-06,  ..., 6.5985e-07,
            4.7161e-07, 1.8596e-03],
           [4.2982e-02, 2.1474e-04, 8.4865e-06,  ..., 1.5975e-06,
            2.3442e-06, 5.2280e-03]]]], grad_fn=<SoftmaxBackward0>),
 tensor([[[[1.0524e-08, 1.0475e-06, 1.0101e-04,  ..., 1.1038e-04,
            6.0925e-04, 6.2322e-01],
           [1.0524e-08, 1.0475e-06, 1.0101e-04,  ..., 1.1038e-04,
            6.0925e-04, 6.2321e-01],
           [2.7616e-02, 9.1683e-03, 2.8237e-03,  ..., 6.5916e-05,
            3.5627e-05, 1.8204e-03],
           ...,
           [1.9481e-03, 2.9789e-05, 5.2240e-07,  ..., 7.7109e-06,
            2.4182e-05, 2.1501e-05],
           [6.3885e-02, 7.7698e-03, 4.8052e-04,  ..., 3.5022e-05,
            4.4574e-05, 2.2987e-03],
           [8.9631e-02, 1.3444e-03, 3.4136e-04,  ..., 4.9747e-06,
            5.9777e-06, 1.6273e-04]],


## Validation and Test cleaning

In [19]:
model_name = "facebook/bart-large-cnn"
tokenizer = BartTokenizer.from_pretrained(model_name)
model = BartForConditionalGeneration.from_pretrained(model_name, output_attentions=True, torch_dtype = torch.bfloat16)

Loading weights: 100%|██████████| 511/511 [00:00<00:00, 980.83it/s, Materializing param=model.encoder.layers.11.self_attn_layer_norm.weight]

In [20]:
validation_path = "document_validation.parquet" #file path
validation = pd.read_parquet(validation_path)

test_path = "document_test.parquet"
test = pd.read_parquet(test_path)

In [21]:
validation['abstract'] = validation['abstract'].str.replace(' \n', '', regex=False) #remove \n
validation['abstract'] = validation['abstract'].str.replace(r'@\w+', '', regex=True) # remove @ formulas
validation['abstract'] = validation['abstract'].str.replace('  ', ' ', regex=False)

validation['article'] = validation['article'].str.replace(r'@\w+', '', regex=True) # remove @ formulas
validation['article'] = validation['article'].str.replace('  ', ' ', regex=False) #replace double space with single space

In [22]:
validation_article_summary = validation['article'].str.len().describe()

validation_article_summary

count      6436.000000
mean      30036.521287
std       19167.893171
min        1028.000000
25%       17368.500000
50%       25678.500000
75%       37804.500000
max      206131.000000
Name: article, dtype: float64

In [23]:
validation_abstract_summary = validation['abstract'].str.len().describe()

validation_abstract_summary

count    6436.000000
mean      929.612803
std       330.412665
min       238.000000
25%       673.750000
50%       905.500000
75%      1172.000000
max      1863.000000
Name: abstract, dtype: float64

In [24]:
validation = validation[validation['article'].str.len() >= validation_article_summary['25%']] 
validation = validation[validation['article'].str.len() <= validation_article_summary['75%']]  

validation = validation[validation['abstract'].str.len() >= validation_abstract_summary['25%']]
validation = validation[validation['abstract'].str.len() <= validation_abstract_summary['75%']]

validation = validation.drop_duplicates()
validation = validation.reset_index(drop=True)

In [25]:
test['abstract'] = test['abstract'].str.replace(' \n', '', regex=False) #remove \n
test['abstract'] = test['abstract'].str.replace(r'@\w+', '', regex=True) # remove @ formulas
test['abstract'] = test['abstract'].str.replace('  ', ' ', regex=False)

test['article'] = test['article'].str.replace(r'@\w+', '', regex=True) # remove @ formulas
test['article'] = test['article'].str.replace('  ', ' ', regex=False) #replace double space with single space

In [26]:
test_article_summary = test['article'].str.len().describe()

test_article_summary

count      6440.000000
mean      30083.701242
std       19607.036626
min         599.000000
25%       17539.750000
50%       25769.000000
75%       38066.000000
max      454025.000000
Name: article, dtype: float64

In [27]:
test_abstract_summary = test['abstract'].str.len().describe()

test_abstract_summary

count    6440.000000
mean      936.243634
std       323.882370
min       203.000000
25%       686.000000
50%       918.500000
75%      1177.250000
max      1814.000000
Name: abstract, dtype: float64

In [28]:
test = test[test['article'].str.len() >= test_article_summary['25%']] 
test = test[test['article'].str.len() <= test_article_summary['75%']]  

test = test[test['abstract'].str.len() >= test_abstract_summary['25%']]
test = test[test['abstract'].str.len() <= test_abstract_summary['75%']]

test = test.drop_duplicates()
test = test.reset_index(drop=True)

## Training

In [29]:
train_dataset = Dataset.from_pandas(document)
validation_dataset   = Dataset.from_pandas(validation)
test_dataset  = Dataset.from_pandas(test)

In [ ]:
label = tokenizer(
    list(train_dataset["abstract"]),
    truncation=True,
    max_length=1024,
    padding=False
)

# Get lengths
label_lengths = [len(ids) for ids in label["input_ids"]]

In [31]:
abstract_tokens_summary = pd.DataFrame(label_lengths).describe()[0]
abstract_tokens_summary

count    15490.000000
mean       193.410781
std         42.827134
min        106.000000
25%        159.000000
50%        189.000000
75%        223.000000
max        544.000000
Name: 0, dtype: float64

In [32]:
token_len_IQR =  abstract_tokens_summary['75%'] - abstract_tokens_summary['25%']
1.5 * token_len_IQR

np.float64(96.0)

In [33]:
abstract_tokens_summary['25%'] - (1.5 * token_len_IQR)

np.float64(63.0)

In [34]:
abstract_tokens_summary['75%'] + (1.5 * token_len_IQR)

#pad to 320 should be a clean number

np.float64(319.0)

In [35]:
import nltk
import evaluate


nltk.download('punkt', quiet=True)
metric = evaluate.load('rouge')

In [30]:
def compute_metrics(eval_preds):
    preds, labels = eval_preds

    # decode preds and labels
    labels = np.where(labels != -100, labels, tokenizer.pad_token_id)
    decoded_preds = tokenizer.batch_decode(preds, skip_special_tokens=True)
    decoded_labels = tokenizer.batch_decode(labels, skip_special_tokens=True)

    # rougeLSum expects newline after each sentence
    decoded_preds = ["\n".join(nltk.sent_tokenize(pred.strip())) for pred in decoded_preds]
    decoded_labels = ["\n".join(nltk.sent_tokenize(label.strip())) for label in decoded_labels]

    result = metric.compute(predictions=decoded_preds, references=decoded_labels, use_stemmer=True)
    return result

In [36]:
model_name = "facebook/bart-large-cnn"
tokenizer = BartTokenizer.from_pretrained(model_name)
model = BartForConditionalGeneration.from_pretrained(model_name, output_attentions=False, torch_dtype = torch.bfloat16).cuda()

Loading weights: 100%|██████████| 511/511 [00:00<00:00, 978.95it/s, Materializing param=model.encoder.layers.11.self_attn_layer_norm.weight]

In [37]:
def tokenize_document(dataset):
    model_input = tokenizer(dataset["article"], max_length = 1024, truncation = True)
    labels = tokenizer(dataset["abstract"], max_length = 320, truncation = True)

    model_input["labels"] = labels['input_ids']
    return model_input

In [38]:
tokenized_dataset = train_dataset.map(tokenize_document, batched=True)

Map: 100%|██████████| 15490/15490 [01:23<00:00, 185.69 examples/s]

In [39]:
from transformers import (
    BartTokenizer,
    BartForConditionalGeneration,
    Seq2SeqTrainer,
    Seq2SeqTrainingArguments,
    DataCollatorForSeq2Seq
)

data_collator = DataCollatorForSeq2Seq(
    tokenizer=tokenizer,
    model=model,
    padding="longest"  # pads to the longest sequence in each batch
)

In [40]:
validation_tokenized = validation_dataset.map(tokenize_document, batched=True, remove_columns=validation_dataset.column_names)
test_tokenized = test_dataset.map(tokenize_document, batched=True, remove_columns=test_dataset.column_names)

Map: 100%|██████████| 1727/1727 [00:10<00:00, 169.92 examples/s]
Map: 100%|██████████| 1715/1715 [00:09<00:00, 176.26 examples/s]

In [41]:
model_name = "facebook/bart-large-cnn"
tokenizer = BartTokenizer.from_pretrained(model_name)
model = BartForConditionalGeneration.from_pretrained(model_name, torch_dtype = torch.bfloat16).cuda()

Loading weights: 100%|██████████| 511/511 [00:00<00:00, 1003.95it/s, Materializing param=model.encoder.layers.11.self_attn_layer_norm.weight]

In [47]:
from transformers import Seq2SeqTrainingArguments

training_args = Seq2SeqTrainingArguments(
    output_dir="./bart_finetuned",      # folder to save checkpoints
    num_train_epochs=2,                  # number of passes through the dataset
    per_device_train_batch_size=4,       # safe for 12GB VRAM
    per_device_eval_batch_size=4,        # same as train batch size
    learning_rate=2e-5,                  # learning rate
    weight_decay=0.01,                   # regularization
    save_total_limit=3,                   # keep last 3 checkpoints
    eval_strategy="epoch",          # evaluate once per epoch
    save_strategy="epoch",                # save checkpoint once per epoch
    logging_strategy="steps",             # log every N steps
    logging_steps=100,                    # adjust if needed
    bf16=True,                            # mixed precision for VRAM efficiency
    predict_with_generate=True            # necessary for seq2seq evaluation
)

In [43]:
trainer = Seq2SeqTrainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_dataset,
    eval_dataset=validation_tokenized,      
    processing_class=tokenizer,
    data_collator=data_collator
)

In [83]:
trainer.train()

Writing model shards: 100%|██████████| 1/1 [00:01<00:00,  1.24s/it]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  2.25it/s]

TrainOutput(global_step=7746, training_loss=2.7847567656044503, metrics={'train_runtime': 2220.0172, 'train_samples_per_second': 13.955, 'train_steps_per_second': 3.489, 'total_flos': 6.778703195406336e+16, 'train_loss': 2.7847567656044503, 'epoch': 2.0})

In [53]:
from transformers import BartForConditionalGeneration, BartTokenizer, Seq2SeqTrainer, Seq2SeqTrainingArguments
from datasets import load_dataset

# Re-load model, tokenizer, dataset, and training arguments
model = BartForConditionalGeneration.from_pretrained(r"bart_finetuned\checkpoint-7746").cuda()
tokenizer = BartTokenizer.from_pretrained(r"bart_finetuned\checkpoint-7746")

Loading weights: 100%|██████████| 512/512 [00:00<00:00, 1230.80it/s, Materializing param=model.shared.weight]

In [ ]:
from transformers import Seq2SeqTrainer

# Set training args — keep num_train_epochs the same or higher than previous total
training_args = Seq2SeqTrainingArguments(
    output_dir="./bart_finetuned",
    num_train_epochs=3,  # total epochs, not additional
    per_device_train_batch_size=4,
    per_device_eval_batch_size=4,
    learning_rate=2e-5,
    weight_decay=0.01,
    save_total_limit=3,
    eval_strategy="epoch",
    save_strategy="epoch",
    logging_strategy="steps",
    logging_steps=100,
    bf16=True,
    predict_with_generate=True
)

In [57]:
trainer = Seq2SeqTrainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_dataset,
    eval_dataset=validation_tokenized,
    processing_class=tokenizer,
    data_collator=data_collator
)

trainer.train(resume_from_checkpoint="./bart_finetuned/checkpoint-7746")

There were missing keys in the checkpoint model loaded: ['model.encoder.embed_tokens.weight', 'model.decoder.embed_tokens.weight', 'lm_head.weight'].

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  1.13it/s]

TrainOutput(global_step=11619, training_loss=0.9223433538151747, metrics={'train_runtime': 1343.412, 'train_samples_per_second': 34.591, 'train_steps_per_second': 8.649, 'total_flos': 1.0135548224077824e+17, 'train_loss': 0.9223433538151747, 'epoch': 3.0})

## ROUGE

In [58]:
import evaluate
import numpy as np

rouge = evaluate.load("rouge")

In [59]:
def compute_metrics(eval_pred):
    predictions, labels = eval_pred

    # If model returns tuple
    if isinstance(predictions, tuple):
        predictions = predictions[0]

    # Decode predictions
    decoded_preds = tokenizer.batch_decode(
        predictions, skip_special_tokens=True
    )

    # Replace -100 in labels (ignore index) so they can be decoded
    labels = np.where(labels != -100, labels, tokenizer.pad_token_id)

    decoded_labels = tokenizer.batch_decode(
        labels, skip_special_tokens=True
    )

    # Strip whitespace
    decoded_preds = [pred.strip() for pred in decoded_preds]
    decoded_labels = [label.strip() for label in decoded_labels]

    result = rouge.compute(
        predictions=decoded_preds,
        references=decoded_labels,
        use_stemmer=True
    )

    return {
        "rouge1": result["rouge1"],
        "rouge2": result["rouge2"],
        "rougeL": result["rougeL"]
    }

## Trained model ROUGE

In [ ]:
#epoch = 2

rouge = evaluate.load("rouge")

predictions = trainer.predict(validation_tokenized)

preds = predictions.predictions
labels = predictions.label_ids

labels = np.where(labels != -100, labels, tokenizer.pad_token_id)

decoded_preds = tokenizer.batch_decode(preds, skip_special_tokens=True)
decoded_labels = tokenizer.batch_decode(labels, skip_special_tokens=True)

results = rouge.compute(
    predictions=decoded_preds,
    references=decoded_labels,
    use_stemmer=True
)

print({k: round(v * 100, 4) for k, v in results.items()})

{'rouge1': np.float64(44.6586), 'rouge2': np.float64(15.9589), 'rougeL': np.float64(24.7595), 'rougeLsum': np.float64(24.7636)}

# ROUGE results from epoch = 2

{'rouge1': np.float64(44.6586), 'rouge2': np.float64(15.9589), 'rougeL': np.float64(24.7595), 'rougeLsum': np.float64(24.7636)}

In [60]:
#epoch = 3

rouge = evaluate.load("rouge")

predictions = trainer.predict(validation_tokenized)

preds = predictions.predictions
labels = predictions.label_ids

labels = np.where(labels != -100, labels, tokenizer.pad_token_id)

decoded_preds = tokenizer.batch_decode(preds, skip_special_tokens=True)
decoded_labels = tokenizer.batch_decode(labels, skip_special_tokens=True)

results = rouge.compute(
    predictions=decoded_preds,
    references=decoded_labels,
    use_stemmer=True
)

print({k: round(v * 100, 4) for k, v in results.items()})

{'rouge1': np.float64(44.6801), 'rouge2': np.float64(15.9898), 'rougeL': np.float64(24.713), 'rougeLsum': np.float64(24.7124)}

# ROUGE results from epoch = 3


{'rouge1': np.float64(44.6801), 'rouge2': np.float64(15.9898), 'rougeL': np.float64(24.713), 'rougeLsum': np.float64(24.7124)}