In [ ]:
import pandas as pd

#### Process Data

In [ ]:
arxiv_data = pd.read_parquet("test-00000-of-00001.parquet")
arxiv_data.head()

,article,abstract
0,for about 20 years the problem of properties o...,the short - term periodicities of the daily su...
1,it is believed that the direct detection of gr...,we study the detectability of circular polariz...
2,"as a common quantum phenomenon , the tunneling...","starting from the wkb approximation , a new ba..."
3,for the hybrid monte carlo algorithm ( hmc)@xc...,we study a novel class of numerical integrator...
4,recently it was discovered that feynman integr...,new methods for obtaining functional equations...

In [ ]:
#make tiny dataset
data_tiny_test = arxiv_data.head(100)
data_tiny_test

,article,abstract
0,for about 20 years the problem of properties o...,the short - term periodicities of the daily su...
1,it is believed that the direct detection of gr...,we study the detectability of circular polariz...
2,"as a common quantum phenomenon , the tunneling...","starting from the wkb approximation , a new ba..."
3,for the hybrid monte carlo algorithm ( hmc)@xc...,we study a novel class of numerical integrator...
4,recently it was discovered that feynman integr...,new methods for obtaining functional equations...
...,...,...
95,the ongoing heavy ion physics program with the...,two major advantages of the star detector - un...
96,"in june 2015 , the large hadron collider ( lhc...",the alice detector has excellent particle iden...
97,hanle effect measurements ( bommier et al . 19...,erupting filaments are sometimes observed to u...
98,noncovalent functionalization of single - wall...,"the stability , electronic and optical propert..."
99,monitoring the activity of large - scale neuro...,in vivo calcium imaging through microscopes ha...

In [ ]:
data_tiny_test.to_csv('test.csv')

In [ ]:
data_tiny_val = arxiv_data.iloc[200:250]

In [ ]:
data_tiny_val.to_csv('val.csv')

#### Create Model

```shell
python run_summarization.py `
     --model_name_or_path facebook/bart-base `
     --do_train `
     --do_eval `
     --train_file ../test.csv `
     --validation_file ../val.csv `
     --output_dir ../test-summarization ` 
     --per_device_train_batch_size=4 `
     --per_device_eval_batch_size=4 `
     --predict_with_generate `
     --text_column article `
     --summary_column abstract
```

#### Test Model

In [ ]:
#random_article = arxiv_data.iloc[500, 0]

from transformers import AutoTokenizer, AutoModelForSeq2SeqLM
model_name = "Veekee/cmpe-252-summary-project"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSeq2SeqLM.from_pretrained(model_name)

text = ""
inputs = tokenizer(text, return_tensors="pt")

outputs = model.generate(**inputs, max_new_tokens=50)
summary = tokenizer.decode(outputs[0], skip_special_tokens=True)

print(summary)

c:\Users\Corinne\Documents\MSAI\CMPE-252\Final_Project\CMPE-252-summary-project\.venv\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Please make sure the generation config includes `forced_bos_token_id=0`.
Loading weights: 100%|██████████| 512/512 [00:00<00:00, 968.66it/s, Materializing param=model.shared.weight]
c:\Users\Corinne\Documents\MSAI\CMPE-252\Final_Project\CMPE-252-summary-project\.venv\lib\site-packages\transformers\generation\utils.py:1716: UserWarning: Unfeasible length constraints: `min_length` (56) is larger than the maximum possible length (51). Generation will stop at the defined maximum length. You should decrease the minimum length and/or increase the maximum length. Note that `max_length` is set to 51, its default value.
  warnings.warn(

“We don’t actually know what normal flatus production looks like,” says the author of the book “Flatulence’s Not a Problem” “It's hard to know when